apiVersion: batch/v1
kind: CronJob
metadata:
  name: docs-backup-cron
spec:
  schedule: "0 23 10 * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: build-docs-job
            image: docker.io/yukics/quartz-job:20260326v1
            imagePullPolicy: IfNotPresent
            volumeMounts:
            - name: docs-storage
              mountPath: /public
            - name: nginx-config-volume
              mountPath: /tmp/custom/quartz.config.ts
              subPath: quartz.config.ts              
            envFrom:
            - configMapRef:
                name: docs-config          
          restartPolicy: OnFailure
          volumes:
          - name: nginx-config-volume
            configMap:
              name: nginx-config          
          - name: docs-storage
            persistentVolumeClaim:
              claimName: docs-pvc