apiVersion: apps/v1
kind: Deployment
metadata:
  name: docs-nginx
  labels:
    app: docs-nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: docs-nginx
  template:
    metadata:
      labels:
        app: docs-nginx
    spec:
      initContainers:
      - name: build-docs
        image: docker.io/yukics/quartz-job:20260326v1
        imagePullPolicy: Always
        volumeMounts:
        - name: docs-storage
          mountPath: /public
        - name: nginx-config-volume
          mountPath: /tmp/custom/quartz.config.ts
          subPath: quartz.config.ts
        envFrom:
        - configMapRef:
            name: docs-config
      containers:
      - name: docs-nginx
        image: nginx:stable-alpine3.23-slim
        ports:
        - containerPort: 80
        volumeMounts:
        - name: nginx-config-volume
          mountPath: /etc/nginx/conf.d/default.conf
          subPath: default.conf
        - name: docs-storage
          mountPath: /usr/share/nginx
          subPath: html
      volumes:
      - name: nginx-config-volume
        configMap:
          name: nginx-config
      - name: docs-storage
        persistentVolumeClaim:
          claimName: docs-pvc