apiVersion: apps/v1
kind: Deployment
metadata:
  name: docs-nginx
  labels:
    app: docs-nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: docs-nginx
  template:
    metadata:
      labels:
        app: docs-nginx
    spec:
      initContainers:
      - name: build-docs
        image: docker.io/yukics/quartz-job:20260326
        imagePullPolicy: Always
        volumeMounts:
        - name: docs-storage
          mountPath: /public
        envFrom:
        - configMapRef:
            name: docs-config
      containers:
      - name: docs-nginx
        image: nginx:stable-alpine3.23-slim
        ports:
        - containerPort: 80
        volumeMounts:
        - name: docs-storage
          mountPath: /usr/share/nginx/html
          subPath: html
      volumes:
      - name: docs-storage
        persistentVolumeClaim:
          claimName: docs-pvc