apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: docs-ingressroute
spec:
  entryPoints:
    - websecure
  tls:
    certResolver: letsencrypt
  routes:
  - kind: Rule
    middlewares:
    #   - name: test-ratelimit
    #     namespace: kube-system
    #   - name: test-inflightreq
    #     namespace: kube-system
      - name: sec-headers
        namespace: kube-system        
    match: Host(`docs.yukics.net`) || Host(`docs.yuki.es`)
    services:
    - kind: Service
      name: docs-nginx-service
      namespace: docs
      passHostHeader: true
      port: 80
    observability:
      accessLogs: true
      traceVerbosity: minimal