apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: docs-ingressroute
spec:
  entryPoints:
    - websecure
  tls:
    certResolver: letsencrypt
  routes:
  - kind: Rule
    match: Host(`docs.yukics.net`)
    services:
    - kind: Service
      name: docs-service
      namespace: docs
      passHostHeader: true
      port: 90
    observability:
      accessLogs: true
      traceVerbosity: minimal